name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.3
  crypto: ^3.0.3
  flutter_colorpicker: ^1.0.3
  cupertino_icons: ^1.0.2
  change_app_package_name: ^1.1.0
  firebase_analytics: ^10.5.0
  firebase_storage: ^11.2.7
  firebase_ui_firestore: ^1.5.12
  email_validator: ^2.1.17
  firebase_ui_auth: ^1.9.1
  firebase_ui_oauth_google: ^1.2.13
  firebase_ui_storage: ^1.0.3
  file_picker: ^4.5.0
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
  - assets/logo.png
  - assets/