// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo_EvgpLeufJ89SboOSqEYxi-wK-4wEY4',
    appId: '1:1026021401044:web:300494bbc8bbd128b43641',
    messagingSenderId: '1026021401044',
    projectId: 'socialpixels-dca76',
    authDomain: 'socialpixels-dca76.firebaseapp.com',
    databaseURL: 'https://socialpixels-dca76-default-rtdb.firebaseio.com',
    storageBucket: 'socialpixels-dca76.appspot.com',
    measurementId: 'G-Y2P2JMH2KW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArfwye53VPevW-CMv-6H685vTOGq2R1tk',
    appId: '1:1026021401044:android:4276e748b7bfd903b43641',
    messagingSenderId: '1026021401044',
    projectId: 'socialpixels-dca76',
    databaseURL: 'https://socialpixels-dca76-default-rtdb.firebaseio.com',
    storageBucket: 'socialpixels-dca76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsT77kOllYYRbsTZHwJR5NS632OfUFHSM',
    appId: '1:1026021401044:ios:488a45a3ed77be54b43641',
    messagingSenderId: '1026021401044',
    projectId: 'socialpixels-dca76',
    databaseURL: 'https://socialpixels-dca76-default-rtdb.firebaseio.com',
    storageBucket: 'socialpixels-dca76.appspot.com',
    iosBundleId: 'com.example.tictactoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsT77kOllYYRbsTZHwJR5NS632OfUFHSM',
    appId: '1:1026021401044:ios:9854cd13836e7980b43641',
    messagingSenderId: '1026021401044',
    projectId: 'socialpixels-dca76',
    databaseURL: 'https://socialpixels-dca76-default-rtdb.firebaseio.com',
    storageBucket: 'socialpixels-dca76.appspot.com',
    iosBundleId: 'com.example.tictactoe.RunnerTests',
  );
}
